import CERW.Model
import CERW.Support.Norm.Freedman

/-!
# lem:freedman

`lem:freedman` of the revised paper (`limit-shapes.tex:448-453`). The bytes between the markers are the
frozen contract recorded in `ledger/manifest.yaml`.
-/

universe u

open MeasureTheory Filter Topology ProbabilityTheory
open scoped symmDiff Pointwise NNReal
open LatticeProb (Site euclidNorm)

/-- `lem:freedman`:

```latex
\begin{lemma}\label{lem:freedman}
Let $p>0$. There exists $C(p)<\infty$ such that the following holds for every integer~$n\geq2$ and every real martingale~$Z$ whose increments have absolute value at most~$1$: with probability at least $1-Cn^{-p}$,
\begin{equation}\label{eq:freedman}
|Z_n-Z_0|\leq C\bigl(\sqrt{\langle Z\rangle_n\log n}+\log n\bigr)\, .
\end{equation}
\end{lemma}
Definitions the statement relies on (verbatim):
\textit{notation for brackets (line 305)}
\item The $\sigma$-field generated by $X_0,\ldots,X_j$ is~$\mathcal F_j$. For martingales $Z_1$ and~$Z_2$, the brackets $\langle Z_1\rangle_n$ and~$\langle Z_1,Z_2\rangle_n$ are the predictable quadratic variation and covariation through time~$n$.
\textit{notation $n\ge2$ (line 308)}
\item All estimates concern integers~$n\geq2$, so that $\log n>0$. In a statement that holds with probability at least $1-Cn^{-p}$ for all sufficiently large~$n$, enlarging~$C$ makes it hold for every $n\geq2$.
```
-/
-- FROZEN-STATEMENT-BEGIN
theorem CERW.Frozen.freedman_bound :
    ∀ p : ℝ, 0 < p → ∃ C : ℝ, 0 < C ∧
      ∀ n : ℕ, 2 ≤ n →
      ∀ {Ω : Type u} [m0 : MeasurableSpace Ω] (μ : Measure Ω) [IsProbabilityMeasure μ]
        (ℱ : Filtration ℕ m0) (Z : ℕ → Ω → ℝ), Martingale Z ℱ μ →
        (∀ᵐ ω ∂μ, ∀ t, |Z (t + 1) ω - Z t ω| ≤ 1) →
        μ {ω | ¬ |Z n ω - Z 0 ω|
            ≤ C * (Real.sqrt (CERW.predBracket μ ℱ Z Z n ω * Real.log n) + Real.log n)}
          ≤ ENNReal.ofReal (C * (n : ℝ) ^ (-p))
-- FROZEN-STATEMENT-END
:= by
  exact @CERW.Support.Norm.freedman_bound
