import CERW.Model
import CERW.Support.Norm.BallLayer

/-!
# lem:layer

`lem:layer` of the revised paper (`limit-shapes.tex:780-785`). The bytes between the markers are the
frozen contract recorded in `ledger/manifest.yaml`.
-/

universe u

open MeasureTheory Filter Topology ProbabilityTheory
open scoped symmDiff Pointwise NNReal
open LatticeProb (Site euclidNorm)

/-- `lem:layer`:

```latex
\begin{lemma}\label{lem:layer}
Let $b\geq0$ and $a>0$, and let $D$ be a measurable subset of $\{v\in\R^d:b\leq \gauge(v)\leq b+a\}$. Then
\begin{equation*}
\sup_{y\in\R^d}|U_D(y)|\leq2d\drift a\, .
\end{equation*}
\end{lemma}
Definitions the statement relies on (verbatim): the potential of a norm (eq:potential-norm, lines 348--352) and the
notation $\Lambda_\gauge,c_\gauge$ (line 327).
For a norm~$\gauge$, the potential~\eqref{eq:potential-intro} is defined with the gradient of~$\gauge$ in place of~$v/|v|$: for a bounded measurable set~$D\subset\R^d$ and $y\in\R^d$, let
\begin{equation}\label{eq:potential-norm}
U_D(y)\coloneqq\frac{2\drift}{\omega_d}\int_D\nabla\gauge(v)\cdot\frac{v-y}{|v-y|^d}\dd v
\end{equation}
be the potential generated by the vector field~$-\drift\nabla\gauge$ on~$D$; for the Euclidean norm it is~\eqref{eq:potential-intro}.
\begin{quote}
In Sections~\ref{sec:norm-setup}--\ref{sec:norms}, $\gauge$ is a norm, $\drift$ satisfies~\eqref{eq:ellipticity}, $r_n$ is given by~\eqref{eq:radius-norm}, and $U_D$ is the potential~\eqref{eq:potential-norm} defined below; at a point~$v\in\R^d$, $\nabla\gauge(v)$ is the gradient, which exists for almost every~$v$. Let $\Lambda_\gauge\coloneqq\max_{|u|=1}\gauge(u)$ and $c_\gauge\coloneqq\min_{|u|=1}\gauge(u)$; every $\xi\in\partial\gauge(x)$ satisfies $\xi\cdot x=\gauge(x)$ and $|\xi|\leq\Lambda_\gauge$. In Sections~\ref{sec:contact}--\ref{sec:lower}, $\gauge$ is the Euclidean norm, so that $\xi(x)=u_x$, $r_n$ is given by~\eqref{eq:radius}, and $U_D$ is the potential~\eqref{eq:potential-intro}.
\end{quote}
```
-/
-- FROZEN-STATEMENT-BEGIN
theorem CERW.Frozen.layer_potential {d : ℕ} (hd : 2 ≤ d)
    {Ψ : EuclideanSpace ℝ (Fin d) → ℝ} (hΨ : CERW.IsNorm Ψ) {ε : ℝ} (hε : 0 < ε)
    {a b : ℝ} (hb : 0 ≤ b) (ha : 0 < a) {D : Set (EuclideanSpace ℝ (Fin d))}
    (hDm : MeasurableSet D) (hD : D ⊆ {v | b ≤ Ψ v ∧ Ψ v ≤ b + a})
    (y : EuclideanSpace ℝ (Fin d)) :
    |CERW.normPotential d ε Ψ D y| ≤ 2 * d * ε * a
-- FROZEN-STATEMENT-END
:= by
  revert y hD hDm D ha hb b a hε ε hΨ Ψ hd d
  exact @CERW.Support.Norm.layer_potential
