import CERW.Model

/-!
# lem:local

`lem:local` of the revised paper (`limit-shapes.tex:384-400`). The bytes between the markers are the
frozen contract recorded in `ledger/manifest.yaml`.
-/

universe u

open MeasureTheory Filter Topology ProbabilityTheory
open scoped symmDiff Pointwise NNReal
open LatticeProb (Site euclidNorm)

/-- `lem:local`:

```latex
\begin{lemma}\label{lem:local}
Let $p>0$. There exists $C(d,\drift,\gauge,p)<\infty$ such that, for every integer~$n\geq2$, the following estimates hold simultaneously with probability at least $1-Cn^{-p}$.
\begin{enumerate}[label=\textup{(\roman*)}]
\item \underline{\emph{Largest local time}}:
\begin{equation}\label{eq:M}
\max_{x\in\Z^d}\ell_n(x)\leq C|A_n|^{\nf{1}{d}}+C(\log n)^2\, .
\end{equation}
\item \underline{\emph{Local times on time intervals}}: for all integers~$0\leq s<t\leq n$,
\begin{equation}\label{eq:interval}
M_{s,t}\leq Ck_{s,t}^{\nf{1}{d}}+C(\log n)^2\, .
\end{equation}
\item \underline{\emph{Approximation by the potential}}: for every $y\in\R^d$ with $|y|\leq2n$,
\begin{equation}\label{eq:approx}
|\widetilde\ell_n(y)-U_{D_n}(y)|\leq C\log n+C\begin{cases}\bigl(\max_x\ell_n(x)\bigr)^{\nf12}\log n,&d=2,\\\bigl(\max_x\ell_n(x)\log n\bigr)^{\nf12},&d\geq3\end{cases}\, .
\end{equation}
\end{enumerate}
\end{lemma}
Definitions the statement relies on (verbatim):
\textit{$M_{s,t}$ and $k_{s,t}$ (lines 377--382)}
For integers~$0\leq s<t\leq n$, let
\begin{equation*}
M_{s,t}\coloneqq\max_{x\in\Z^d}\sum_{s\leq j<t}\ind_{\{X_j=x\}}
\qquad\text{and}\qquad
k_{s,t}\coloneqq\sum_{s\leq j<t}I_j\, .
\end{equation*}
\textit{notation $I_j$, $\widetilde\ell_n$, $n\ge2$ (lines 297--299)}
\item The indicator that the step at time~$j$ is a first departure is $I_j\coloneqq\ind_{\{X_j\notin A_j\}}$, so that $\E(X_{j+1}-X_j\mid\mathcal F_j)=-\drift I_j\xi(X_j)$, where $\xi(x)=u_x$ for the Euclidean norm.
\item The function~$\widetilde\ell_n$ on~$\R^d$ equals $\ell_n(x)$ on~$C_x$ for every $x\in\Z^d$; it vanishes off~$D_n$.
\item All estimates concern integers~$n\geq2$, so that $\log n>0$. In a statement that holds with probability at least $1-Cn^{-p}$ for all sufficiently large~$n$, enlarging~$C$ makes it hold for every $n\geq2$.
\textit{$D_n$ (lines 122--122)}
Replace each site~$x\in A_n$ by the unit cell~$C_x\coloneqq x+[-\nf12,\nf12)^d$, and let $D_n\coloneqq\bigcup_{x\in A_n}C_x$. The \defn{inner radius} and the \defn{outer radius} are
\textit{eq:potential-norm (lines 348--352)}
For a norm~$\gauge$, the potential~\eqref{eq:potential-intro} is defined with the gradient of~$\gauge$ in place of~$v/|v|$: for a bounded measurable set~$D\subset\R^d$ and $y\in\R^d$, let
\begin{equation}\label{eq:potential-norm}
U_D(y)\coloneqq\frac{2\drift}{\omega_d}\int_D\nabla\gauge(v)\cdot\frac{v-y}{|v-y|^d}\dd v
\end{equation}
be the potential generated by the vector field~$-\drift\nabla\gauge$ on~$D$; for the Euclidean norm it is~\eqref{eq:potential-intro}.
```
-/
-- FROZEN-STATEMENT-BEGIN
theorem CERW.Frozen.norm_local_time_potential {d : ℕ} (hd : 2 ≤ d) :
    ∀ Ψ : EuclideanSpace ℝ (Fin d) → ℝ, CERW.IsNorm Ψ →
    ∀ ε : ℝ, 0 < ε → (∀ i : Fin d, ε * Ψ (CERW.coordVec i) < 1 / (d : ℝ)) →
    ∀ p : ℝ, 0 < p → ∃ C : ℝ, 0 < C ∧
      ∀ ξ : Site d → EuclideanSpace ℝ (Fin d),
        (∀ x : Site d, x ≠ 0 → CERW.IsSubgradient Ψ (CERW.toSpace x) (ξ x)) → ξ 0 = 0 →
      ∀ {Ω : Type u} [MeasurableSpace Ω] (μ : Measure Ω) [IsProbabilityMeasure μ]
        (X : ℕ → Ω → Site d), CERW.IsDriftCERW μ ε ξ X → ∀ n : ℕ, 2 ≤ n →
        μ {ω | ¬ ((CERW.maxLocalTime (X · ω) n : ℝ)
                    ≤ C * ((CERW.departureRange (X · ω) n).card : ℝ) ^ ((1 : ℝ) / d)
                      + C * Real.log n ^ 2 ∧
                  (∀ s t : ℕ, s < t → t ≤ n →
                    (CERW.intervalMax (X · ω) s t : ℝ)
                      ≤ C * (CERW.freshCount (X · ω) s t : ℝ) ^ ((1 : ℝ) / d)
                        + C * Real.log n ^ 2) ∧
                  ∀ y : EuclideanSpace ℝ (Fin d), ‖y‖ ≤ 2 * n →
                    |CERW.cellLocalTime (X · ω) n y
                        - CERW.normPotential d ε Ψ (CERW.cellSet (X · ω) n) y|
                      ≤ C * Real.log n + C *
                        (if d = 2 then Real.sqrt (CERW.maxLocalTime (X · ω) n) * Real.log n
                          else Real.sqrt (CERW.maxLocalTime (X · ω) n * Real.log n)))}
          ≤ ENNReal.ofReal (C * (n : ℝ) ^ (-p))
-- FROZEN-STATEMENT-END
:= by
  sorry
