import CERW.Model
import CERW.Support.Norm.Geometry

/-!
# lem:geometry

`lem:geometry` of the revised paper (`limit-shapes.tex:510-528`). The bytes between the markers are the
frozen contract recorded in `ledger/manifest.yaml`.
-/

universe u

open MeasureTheory Filter Topology ProbabilityTheory
open scoped symmDiff Pointwise NNReal
open LatticeProb (Site euclidNorm)

/-- `lem:geometry`:

```latex
\begin{lemma}\label{lem:geometry}
There exists $C(d,\gauge)<\infty$ such that, for every $\drift>0$, not necessarily satisfying~\eqref{eq:ellipticity}, and every bounded measurable set~$D\subset\R^d$, the following hold.
\begin{enumerate}[label=\textup{(\roman*)}]
\item \underline{\emph{Bound}}:
\begin{equation}\label{eq:potential-bound}
\sup_{y\in\R^d}|U_D(y)|\leq C\drift|D|^{\nf{1}{d}}\, .
\end{equation}
\item \underline{\emph{H\"older continuity}}: for all $y,z\in\R^d$,
\begin{equation}\label{eq:holder}
|U_D(y)-U_D(z)|\leq C\drift|D|^{\nf{1}{(2d)}}|y-z|^{\nf{1}{2}}\, .
\end{equation}
\item \underline{\emph{Spherical averages}}: for all $s>0$,
\begin{equation}\label{eq:newton}
\frac1{d\omega_ds^{d-1}}\int_{\{|v|=s\}}U_D(v)\dd S(v)
=\frac{2\drift}{\omega_d}\int_{D\cap\{|v|>s\}}\frac{\gauge(v)}{|v|^d}\dd v\, .
\end{equation}
The right side of~\eqref{eq:newton} lies between $2d\drift c_\gauge F(s)$ and $2d\drift\Lambda_\gauge F(s)$, and it equals $2d\drift F(s)$ for the Euclidean norm.
\end{enumerate}
\end{lemma}
Definitions the statement relies on (verbatim):
\textit{eq:Fdef (lines 504--508)}
\begin{equation}\label{eq:Fdef}
F(s)\coloneqq\frac1{d\omega_d}\int_{D\cap\{|v|>s\}}|v|^{1-d}\dd v
\leq\frac{|D|}{d\omega_ds^{d-1}}\, .
\end{equation}
The function~$F$ is nonincreasing and continuous. We write $\dd S$ for surface measure on a sphere.
\textit{$\Lambda_\gauge$, $c_\gauge$ (lines 328--328)}
In Sections~\ref{sec:norm-setup}--\ref{sec:norms}, $\gauge$ is a norm, $\drift>0$ satisfies~\eqref{eq:ellipticity}, $r_n$ is given by~\eqref{eq:radius-norm}, and $U_D$ is the potential~\eqref{eq:potential-norm} defined below. At a point~$v\in\R^d$, $\nabla\gauge(v)$ is the gradient, which exists for almost every~$v$. Let $\Lambda_\gauge\coloneqq\max_{|u|=1}\gauge(u)$ and $c_\gauge\coloneqq\min_{|u|=1}\gauge(u)$. Every $\xi\in\partial\gauge(x)$ satisfies $\xi\cdot x=\gauge(x)$ and $|\xi|\leq\Lambda_\gauge$. In Sections~\ref{sec:contact}--\ref{sec:lower}, $\gauge$ is the Euclidean norm, so that $\xi(x)=u_x$, $r_n$ is given by~\eqref{eq:radius}, and $U_D$ is the potential~\eqref{eq:potential-intro}.
\textit{eq:potential-norm (lines 349--353)}
For a norm~$\gauge$, the potential~\eqref{eq:potential-intro} is defined with the gradient of~$\gauge$ in place of~$v/|v|$: for a bounded measurable set~$D\subset\R^d$ and $y\in\R^d$, let
\begin{equation}\label{eq:potential-norm}
U_D(y)\coloneqq\frac{2\drift}{\omega_d}\int_D\nabla\gauge(v)\cdot\frac{v-y}{|v-y|^d}\dd v
\end{equation}
be the potential generated by the vector field~$-\drift\nabla\gauge$ on~$D$. For the Euclidean norm it is~\eqref{eq:potential-intro}.
```
-/
-- FROZEN-STATEMENT-BEGIN
theorem CERW.Frozen.norm_potential_geometry {d : ℕ} (hd : 2 ≤ d) :
    let ωd : ℝ := (volume (Metric.ball (0 : EuclideanSpace ℝ (Fin d)) 1)).toReal
    ∀ Ψ : EuclideanSpace ℝ (Fin d) → ℝ, CERW.IsNorm Ψ → ∃ C : ℝ, 0 < C ∧ ∀ ε : ℝ, 0 < ε →
      ∀ D : Set (EuclideanSpace ℝ (Fin d)), MeasurableSet D → Bornology.IsBounded D →
        let R : ℝ := (volume D).toReal
        (∀ y, |CERW.normPotential d ε Ψ D y| ≤ C * ε * R ^ ((1 : ℝ) / d)) ∧
        (∀ y z, |CERW.normPotential d ε Ψ D y - CERW.normPotential d ε Ψ D z|
            ≤ C * ε * R ^ ((1 : ℝ) / (2 * d)) * ‖y - z‖ ^ ((1 : ℝ) / 2)) ∧
        (∀ s : ℝ, 0 < s →
          let A : ℝ := (d * ωd)⁻¹ * ∫ θ,
              CERW.normPotential d ε Ψ D (s • (θ : EuclideanSpace ℝ (Fin d)))
              ∂(volume : Measure (EuclideanSpace ℝ (Fin d))).toSphere
          let B : ℝ := 2 * ε / ωd * ∫ v in D ∩ {v | s < ‖v‖}, Ψ v / ‖v‖ ^ d
          A = B ∧ 2 * d * ε * CERW.normMin Ψ * CERW.tail d D s ≤ B ∧
            B ≤ 2 * d * ε * CERW.normMax Ψ * CERW.tail d D s ∧
            ((∀ v, Ψ v = ‖v‖) → B = 2 * d * ε * CERW.tail d D s))
-- FROZEN-STATEMENT-END
:= by
  revert hd d
  exact @CERW.Support.Norm.norm_potential_geometry
