import CERW.Model
import CERW.Support.Norm.BallLayer

/-!
# lem:ballpotential

`lem:ballpotential` of the revised paper (`limit-shapes.tex:360-365`). The bytes between the markers are the
frozen contract recorded in `ledger/manifest.yaml`.
-/

universe u

open MeasureTheory Filter Topology ProbabilityTheory
open scoped symmDiff Pointwise NNReal
open LatticeProb (Site euclidNorm)

/-- `lem:ballpotential`:

```latex
\begin{lemma}[The potential of a norm ball]\label{lem:ballpotential}
Let $\gauge$ be a norm, let $\rho>0$, and let $y\in\R^d$. Then
\begin{equation}\label{eq:ballpotential}
U_{\{\gauge<\rho\}}(y)=2d\drift(\rho-\gauge(y))_+\, .
\end{equation}
\end{lemma}
Definitions the statement relies on (verbatim):
\textit{eq:potential-norm (lines 348--352)}
For a norm~$\gauge$, the potential~\eqref{eq:potential-intro} is defined with the gradient of~$\gauge$ in place of~$v/|v|$: for a bounded measurable set~$D\subset\R^d$ and $y\in\R^d$, let
\begin{equation}\label{eq:potential-norm}
U_D(y)\coloneqq\frac{2\drift}{\omega_d}\int_D\nabla\gauge(v)\cdot\frac{v-y}{|v-y|^d}\dd v
\end{equation}
be the potential generated by the vector field~$-\drift\nabla\gauge$ on~$D$; for the Euclidean norm it is~\eqref{eq:potential-intro}.
```
-/
-- FROZEN-STATEMENT-BEGIN
theorem CERW.Frozen.norm_ball_potential {d : ℕ} (hd : 2 ≤ d)
    {Ψ : EuclideanSpace ℝ (Fin d) → ℝ} (hΨ : CERW.IsNorm Ψ) (ε : ℝ) {ρ : ℝ} (hρ : 0 < ρ)
    (y : EuclideanSpace ℝ (Fin d)) :
    CERW.normPotential d ε Ψ {v | Ψ v < ρ} y = 2 * d * ε * max (ρ - Ψ y) 0
-- FROZEN-STATEMENT-END
:= by
  revert y hρ ρ ε hΨ Ψ hd d
  exact @CERW.Support.Norm.norm_ball_potential
