import CERW.Generic.Martingale.LilLower.SignSequence
import Mathlib.Probability.ConditionalExpectation
import Mathlib.Probability.Distributions.Uniform
import Mathlib.Probability.Independence.InfinitePi

/-!
# A coin space carrying an adapted sign sequence

Independent fair coins on `ℕ → Bool`, with `ε j ξ = ±1` according to the `j`-th coin and `𝒦 n` the
σ-algebra generated by the coins `0, …, n`, give a sign sequence.
-/

namespace CERW.Generic.Martingale.LilLower

open MeasureTheory ProbabilityTheory

/-- The fair-coin measure on `Bool`. -/
private noncomputable def fairCoin : Measure Bool := (PMF.uniformOfFintype Bool).toMeasure

/-- The fair-coin measure is a probability measure. -/
private instance : IsProbabilityMeasure fairCoin := by
  unfold fairCoin
  infer_instance

/-- The σ-algebra on `ℕ → Bool` generated by the `i`-th coin. -/
private abbrev coinAlgebra (i : ℕ) : MeasurableSpace (ℕ → Bool) :=
  MeasurableSpace.comap (fun ξ : ℕ → Bool => ξ i) ⊤

/-- The σ-algebra on `ℕ → Bool` generated by the coins `0, …, n`. -/
private abbrev coinAlgebraUpTo (n : ℕ) : MeasurableSpace (ℕ → Bool) :=
  ⨆ i ∈ Set.Iic n, coinAlgebra i

/-- The sign `±1` of the `j`-th coin. -/
private def coinSign (j : ℕ) (ξ : ℕ → Bool) : ℝ := if ξ j then 1 else -1

/-- Each coin σ-algebra lies in the product σ-algebra. -/
private lemma coinAlgebra_le (i : ℕ) : coinAlgebra i ≤ MeasurableSpace.pi :=
  (measurable_pi_apply i).comap_le

/-- The sign of a fair coin has mean zero. -/
private lemma integral_coinSign (j : ℕ) :
    ∫ ξ, coinSign j ξ ∂(Measure.infinitePi fun _ : ℕ => fairCoin) = 0 := by
  have h := integral_map (μ := Measure.infinitePi fun _ : ℕ => fairCoin)
    (φ := fun ξ : ℕ → Bool => ξ j) (measurable_pi_apply j).aemeasurable
    (f := fun b : Bool => if b then (1 : ℝ) else -1) (measurable_of_finite _).aestronglyMeasurable
  rw [Measure.infinitePi_map_eval] at h
  have h2 : ∫ ξ, coinSign j ξ ∂(Measure.infinitePi fun _ : ℕ => fairCoin) =
      ∫ b : Bool, (if b then (1 : ℝ) else -1) ∂fairCoin := h.symm
  rw [h2, integral_fintype Integrable.of_finite]
  simp [fairCoin, Measure.real]

/-- The coins `0, …, j` are independent of the coin `j + 1`. -/
private lemma indep_coinAlgebraUpTo (j : ℕ) :
    Indep (coinAlgebraUpTo j) (coinAlgebra (j + 1))
      (Measure.infinitePi fun _ : ℕ => fairCoin) := by
  have hind : iIndep coinAlgebra (Measure.infinitePi fun _ : ℕ => fairCoin) :=
    iIndepFun_infinitePi (P := fun _ : ℕ => fairCoin) (X := fun _ => id) (fun _ => measurable_id)
  have hdisj : Disjoint (Set.Iic j) {j + 1} := Set.disjoint_left.2 fun a ha hb => by
    simp only [Set.mem_Iic, Set.mem_singleton_iff] at ha hb
    omega
  simpa [coinAlgebraUpTo] using indep_iSup_of_disjoint coinAlgebra_le hind hdisj

/-- The `i`-th coin σ-algebra lies in the σ-algebra of the coins `0, …, n` when `i ≤ n`. -/
private lemma coinAlgebra_le_coinAlgebraUpTo {i n : ℕ} (h : i ≤ n) :
    coinAlgebra i ≤ coinAlgebraUpTo n :=
  le_iSup₂ (f := fun i (_ : i ∈ Set.Iic n) => coinAlgebra i) i h

/-- The sign of the `j`-th coin is measurable for the `j`-th coin σ-algebra. -/
private lemma stronglyMeasurable_coinSign (j : ℕ) :
    StronglyMeasurable[coinAlgebra j] (coinSign j) := by
  have hm : Measurable[coinAlgebra j] (fun ξ : ℕ → Bool => ξ j) := comap_measurable _
  exact ((measurable_of_finite (fun b : Bool => if b then (1 : ℝ) else -1)).comp
    hm).stronglyMeasurable

/-- There is a probability space with an adapted sequence of signs. -/
theorem exists_signSequence :
    ∃ (Ξ : Type) (_mΞ : MeasurableSpace Ξ) (ν : Measure Ξ), IsProbabilityMeasure ν ∧
      ∃ (𝒦 : ℕ → MeasurableSpace Ξ) (ε : ℕ → Ξ → ℝ), SignSequence ν 𝒦 ε := by
  refine ⟨ℕ → Bool, MeasurableSpace.pi, Measure.infinitePi fun _ : ℕ => fairCoin, inferInstance,
    coinAlgebraUpTo, coinSign, ?_, ?_, ?_, ?_, ?_⟩
  · exact fun m n hmn => biSup_mono fun i hi => hi.trans hmn
  · exact fun n => iSup₂_le fun i _ => coinAlgebra_le i
  · exact fun j => (stronglyMeasurable_coinSign (j + 1)).mono
      (coinAlgebra_le_coinAlgebraUpTo le_rfl)
  · intro j ξ
    unfold coinSign
    split_ifs <;> norm_num
  · intro j
    have h := condExp_indep_eq (coinAlgebra_le _) (iSup₂_le fun i _ => coinAlgebra_le i)
      (stronglyMeasurable_coinSign (j + 1)) (indep_coinAlgebraUpTo j).symm
    rw [integral_coinSign] at h
    exact h

end CERW.Generic.Martingale.LilLower
