"""Write ASSUMPTIONS.md: every result this development assumes, with its
statement, quoted verbatim from the frozen Lean block.

A reader who is told that something is assumed should be able to see exactly
what.  This lists each node whose `state` is `FROZEN`, with where the paper
cites it and the verbatim Lean proposition that is assumed — read with
`lean_source.frozen_blocks` / `lean_source.block_body`, never re-parsed by
hand, so the quote can never drift from what `check_manifest` hashes.

    python3 -m leanform_tools.assumptions <repo>            # write ASSUMPTIONS.md
    python3 -m leanform_tools.assumptions <repo> --check    # fail if stale

If a repo has zero `FROZEN` nodes the correct file says "Nothing." — that is
a declared-vacuity pass (`res.vacuous_ok`), not the zero-node meta-check
failure that a checker earns by inspecting nothing it was supposed to.  But
if the manifest has zero `FROZEN` nodes and someone has hand-edited
ASSUMPTIONS.md to say otherwise, that is a real failure and is reported as
one — vacuity is declared only once the file is confirmed to already say the
one true vacuous thing.
"""

from __future__ import annotations

import sys
from pathlib import Path

from . import lean_source as ls
from .config import RepoConfig, load
from .gate import Result, run

# Assumed-but-also-proved companions: some FROZEN externals are additionally
# discharged by a `*Proved.lean` file elsewhere in the repo (a SEALED or
# PROVED node of its own). This mirrors every surveyed repo's identical
# `companions()` helper.
_COMPANION_SUFFIX = "Proved.lean"
_COMPANION_STATES = ("SEALED", "PROVED")


def frozen_block_text(cfg: RepoConfig, node) -> str:
    """The verbatim, hashed bytes of `node`'s frozen block."""
    if not node.file:
        raise ValueError(f"{node.id}: no file: recorded")
    path = cfg.root / node.file
    src = path.read_text(encoding="utf-8")
    spans = ls.frozen_blocks(src)
    if len(spans) != 1:
        raise ValueError(
            f"{node.id}: {len(spans)} frozen blocks in {node.file}, want exactly 1"
        )
    span = spans[0]
    if span[1] < 0:
        raise ValueError(f"{node.id}: unterminated frozen block in {node.file}")
    return ls.block_body(src, span).strip("\n")


def companions(nodes) -> dict:
    """Map a FROZEN node's file stem to the `*Proved.lean` node discharging it."""
    out = {}
    for n in nodes:
        f = n.file
        if n.state in _COMPANION_STATES and f and f.endswith(_COMPANION_SUFFIX):
            out[Path(f).name[: -len(_COMPANION_SUFFIX)]] = n
    return out


def render(cfg: RepoConfig) -> str:
    assumed = [n for n in cfg.nodes if n.state == "FROZEN"]
    comp = companions(cfg.nodes)
    out = ["# What this development assumes", ""]

    if not assumed:
        out += [
            "Nothing.  Every registered statement in this repository is "
            "proved here, from Mathlib and the libraries this development "
            "builds on; no result is carried as an assumed hypothesis.",
            "",
        ]
        return "\n".join(out)

    out += [
        "The results below are quoted by the paper from the literature and "
        "are **not proved here**.  Each is a proposition carried as an "
        "explicit hypothesis by every theorem whose proof uses it, so a "
        "theorem's statement shows exactly which of these it rests on.",
        "",
        f"There are {len(assumed)} of them.  Each entry gives the node id, "
        "where the paper cites the result, and the verbatim Lean "
        "proposition that is assumed.",
        "",
        "This file is generated by `python3 -m leanform_tools.assumptions` "
        "from `ledger/manifest.yaml` and the Lean sources; do not edit it by "
        "hand.",
        "",
    ]

    withproof = [n for n in assumed if n.file and Path(n.file).stem in comp]
    if withproof:
        verb = "is" if len(withproof) == 1 else "are"
        out += [
            f"Of these, **{len(withproof)} {verb} also proved in this "
            "repository (DISCHARGED)** and so need not be taken on trust; "
            "each is marked below with the companion that proves it.  The "
            f"remaining **{len(assumed) - len(withproof)}** are assumed "
            "outright.",
            "",
        ]

    for n in sorted(assumed, key=lambda x: x.id):
        c = comp.get(Path(n.file).stem) if n.file else None
        decls = ", ".join(f"`{d}`" for d in n.decls) if n.decls else "`<no decls>`"
        out += [
            f"## `{n.id}`",
            "",
            f"* **Lean name** {decls}",
            f"* **File** `{n.file}`",
            f"* **Cited at** {n.source}",
            (
                f"* **DISCHARGED** — also proved here by `{c.id}` in "
                f"`{c.file}`, so this hypothesis can be discharged rather "
                "than assumed"
                if c
                else "* **Not proved here**: this one is assumed outright"
            ),
            "",
            "```lean",
            frozen_block_text(cfg, n),
            "```",
            "",
        ]
    return "\n".join(out)


def check(res: Result, cfg: RepoConfig, write: bool = False) -> None:
    assumed = [n for n in cfg.nodes if n.state == "FROZEN"]
    text = render(cfg)
    target = cfg.root / "ASSUMPTIONS.md"
    current = target.read_text(encoding="utf-8") if target.exists() else None
    stale = current != text

    if assumed:
        res.count(len(assumed))
        res.total = len(cfg.nodes)

    if stale and write:
        target.write_text(text, encoding="utf-8")
        stale = False

    if stale:
        if assumed:
            res.fail(
                f"{target.name} is stale ({len(assumed)} assumed result(s) "
                "recorded in the manifest); rerun with --write"
            )
        else:
            # A real disagreement even though there is nothing to enumerate:
            # someone hand-edited a file that should mechanically say
            # "Nothing." — this must not be waived by res.vacuous_ok.
            res.count()
            res.fail(
                f"{target.name} is stale: the manifest records zero FROZEN "
                "nodes but the file does not say so — a hand-edited number "
                "inside a generated file"
            )
    elif not assumed:
        res.vacuous_ok = "no FROZEN nodes in ledger/manifest.yaml — nothing is assumed"


def main(argv: list[str]) -> int:
    args = argv[1:]
    # Unlike `sync_docs`, this keeps the incumbent scripts' convention: bare
    # invocation regenerates ASSUMPTIONS.md, and `--check` is the opt-in
    # verify-only mode that fails instead of writing.
    write = "--check" not in args
    positional = [a for a in args if not a.startswith("--")]
    root = positional[0] if positional else "."
    cfg = load(root)
    return run("assumptions", check, cfg, write=write)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
