"""Regenerate the manifest-derived tables in README.md, CORRESPONDENCE.md, and
(where present) PROOF.md and formalization.yaml.

Every one of these files restates something `ledger/manifest.yaml` already
records: how many nodes exist, what state each is in, and where in the paper
each one comes from.  Restated facts go stale — three of the surveyed repos
prove it (GMC's README, Parking's PROOF.md, Manhattan's stale `sealed` rows;
see BEST_PRACTICES.md section 0).  Everything between a BEGIN/END marker pair
below is generated from the manifest, so the prose in those files can never
disagree with the checker again, and a hand-edited number inside a marker
pair is a failure, not a correction.

    python3 -m leanform_tools.sync_docs <repo>            # check
    python3 -m leanform_tools.sync_docs <repo> --write    # regenerate in place

Bug this module exists to not reproduce: the incumbent `status_block` in
three vendored copies computed the sealed count as ``len(nodes) - len(draft)``
(or simply reported `counts["SEALED"]` while dropping `CONDITIONAL` from the
header entirely).  Both undercount or overcount the moment a repo has
`CONDITIONAL` or `PROVED` nodes, because `len(nodes) - len(draft)` folds
`CONDITIONAL` and `FROZEN` nodes into "sealed".  On Exploding-Sandpiles'
manifest (4 SEALED, 2 CONDITIONAL, 2 FROZEN, 16 DRAFT_SORRY, 24 total) that
formula prints "8 sealed" — double the true count.  Every state below is
counted exactly and separately from `collections.Counter`, never derived by
subtraction, and named explicitly in the generated prose.
"""

from __future__ import annotations

import re
import sys
from collections import Counter
from pathlib import Path

from .config import RepoConfig, load
from .gate import Result, run

# ---- markers --------------------------------------------------------------
# Kept byte-identical to what is already committed in every surveyed repo's
# README.md / CORRESPONDENCE.md, even though the invocation moved from
# `tools/sync_docs.py` to `python3 -m leanform_tools.sync_docs`: the marker
# text is what `find()` has to match on disk, and this package never writes
# to a repo it wasn't asked to.
STATUS_BEGIN = "<!-- STATUS-BEGIN (generated by tools/sync_docs.py) -->"
STATUS_END = "<!-- STATUS-END -->"
SURFACE_BEGIN = "<!-- FROZEN-SURFACE-BEGIN (generated by tools/sync_docs.py) -->"
SURFACE_END = "<!-- FROZEN-SURFACE-END -->"

_MARKDOWN_BLOCKS = (
    (STATUS_BEGIN, STATUS_END),
    (SURFACE_BEGIN, SURFACE_END),
)

LABEL_RE = re.compile(r"label ([A-Za-z][A-Za-z0-9:_-]*)")

# Canonical, exact, separate-per-state vocabulary used in generated prose.
# FROZEN is named "assumed" here, never "frozen": section 1 of
# BEST_PRACTICES.md is explicit that "Frozen" always means hash-pinned, while
# the *state* `FROZEN` means assumed-not-proved, and both must be said.
STATE_LABEL = {
    "SEALED": "sealed",
    "PROVED": "proved",
    "CONDITIONAL": "conditional",
    "FROZEN": "assumed",
    "DRAFT_SORRY": "draft",
}
STATE_ORDER = ["SEALED", "PROVED", "CONDITIONAL", "FROZEN", "DRAFT_SORRY"]


# ---- FROZEN-SURFACE table --------------------------------------------------


def paper_cell(node, cfg: RepoConfig) -> str:
    """The `paper` column: line range plus label, or the node's own wording.

    Uses `cfg.source_re`, built from `source_pin.file`, never a literal paper
    stem — that literal is exactly the bug this package exists to remove.
    """
    source = node.source or ""
    m = cfg.source_re.match(source)
    lab = LABEL_RE.search(source)
    if m and lab:
        return f"`{cfg.paper_stem}:{m.group('a')}-{m.group('b')}`, `{lab.group(1)}`"
    return source


def _decls_cell(node) -> str:
    decls = node.decls
    if not decls:
        return "`<no decls>`"
    return ", ".join(f"`{d}`" for d in decls)


def surface_table(cfg: RepoConfig) -> str:
    rows = ["| id | Lean | paper | state |", "|---|---|---|---|"]
    for n in cfg.nodes:
        rows.append(
            f"| `{n.id}` | {_decls_cell(n)} | {paper_cell(n, cfg)} | {n.state} |"
        )
    return "\n".join(rows)


# ---- STATUS block -----------------------------------------------------------


def status_block(cfg: RepoConfig) -> str:
    nodes = cfg.nodes
    counts = Counter(n.state for n in nodes)
    total = len(nodes)

    present = [s for s in STATE_ORDER if counts.get(s)]
    unknown = sorted(s for s in counts if s not in STATE_ORDER)
    tally_parts = [f"{counts[s]} {STATE_LABEL[s]}" for s in present]
    tally_parts += [f"{counts[s]} {s!r} (unrecognized state)" for s in unknown]
    tally = ", ".join(tally_parts)

    sealed = counts.get("SEALED", 0)
    proved = counts.get("PROVED", 0)
    conditional = counts.get("CONDITIONAL", 0)
    frozen = counts.get("FROZEN", 0)
    draft = counts.get("DRAFT_SORRY", 0)
    draft_ids = sorted(n.id for n in nodes if n.state == "DRAFT_SORRY")

    sentences: list[str] = []
    if sealed or proved:
        parts = []
        if sealed:
            parts.append(f"{sealed} sealed")
        if proved:
            parts.append(f"{proved} proved")
        sentences.append(
            "The " + " and ".join(parts) + " statements are machine-checked: "
            "complete proofs whose axiom closure contains no `sorryAx`."
        )
    if conditional:
        sentences.append(
            f"The {conditional} conditional node(s) have a complete proof of "
            "their own that applies a `DRAFT_SORRY` predecessor, so their "
            "axiom closure carries `sorryAx` until that predecessor is sealed."
        )
    if frozen:
        sentences.append(
            f"The {frozen} assumed (`FROZEN`) node(s) are cited results, "
            f"stated in `{cfg.lib_name}/External/` and carried as explicit "
            "hypotheses by the theorems that use them; they are assumed here, "
            "not proved."
        )
    if draft:
        if draft_ids and len(draft_ids) <= 8:
            which = ", ".join(f"`{i}`" for i in draft_ids)
            sentences.append(
                f"The {draft} draft node(s) — {which} — have frozen "
                "statements and a single registered `sorry` each; nothing "
                "else is open."
            )
        else:
            sentences.append(
                f"The {draft} draft node(s) have frozen statements and a "
                "single registered `sorry` each; the table below says which."
            )

    body = "  ".join(sentences)
    return f"Status: **{total} registered statements — {tally}.**  {body}"


# ---- generic marker splice --------------------------------------------------


def _apply_marker(
    text: str, begin: str, end: str, body: str, rel: str, res: Result
) -> tuple[str, bool]:
    """If `begin` occurs in `text`, verify/replace that block.

    Returns `(possibly-updated text, whether the marker was present)`.  A
    file that does not carry a given marker pair is not this checker's job
    for that block — README.md normally carries STATUS only and
    CORRESPONDENCE.md SURFACE only, and neither file is required to carry
    both, so absence of one marker type is not itself a failure.
    """
    i = text.find(begin)
    if i < 0:
        return text, False
    j = text.find(end, i)
    if j < 0:
        res.fail(f"{rel}: {begin!r} has no matching {end!r}")
        return text, True
    wanted = text[:i] + begin + "\n\n" + body + "\n\n" + text[j:]
    return wanted, True


def _sync_markdown_file(
    path: Path, cfg: RepoConfig, res: Result, write: bool, required: bool
) -> None:
    rel = str(path.relative_to(cfg.root))
    if not path.exists():
        if required:
            res.fail(f"{rel} does not exist")
        return

    status = status_block(cfg)
    surface = surface_table(cfg)
    original = path.read_text(encoding="utf-8")
    text = original
    any_marker = False
    for begin, end, body in (
        (STATUS_BEGIN, STATUS_END, status),
        (SURFACE_BEGIN, SURFACE_END, surface),
    ):
        text, present = _apply_marker(text, begin, end, body, rel, res)
        any_marker = any_marker or present

    if not any_marker:
        if path.name == "PROOF.md":
            res.fail(
                f"{rel} exists with no generated STATUS/FROZEN-SURFACE marker; "
                "its status paragraph is hand-maintained and will drift "
                "(BEST_PRACTICES.md section 3, new-gate 7) — wrap it in "
                f"{STATUS_BEGIN!r} / {STATUS_END!r} so sync_docs can own it"
            )
        else:
            res.fail(f"{rel} has no generated marker block; sync_docs has nothing to check")
        return

    res.count()
    if text == original:
        return
    if write:
        path.write_text(text, encoding="utf-8")
    else:
        res.fail(
            f"{rel}: generated block(s) disagree with ledger/manifest.yaml "
            "— rerun with --write"
        )


# ---- formalization.yaml tallies (BEST_PRACTICES section 3, new-gate 7) -----

# Vocabulary observed in the corpus (Manhattan-Transience, GMC-formalization-
# private): a `status:` field under `alignment.statements` uses one of these
# words per manifest state.  `FROZEN`/`CONDITIONAL` synonyms are not attested
# in the surveyed corpus (neither repo has a live row for them here) and are
# filled in by analogy with `STATE_LABEL` above, documented so a reviewer can
# correct them if a repo's convention differs.
STATUS_SYNONYMS = {
    "SEALED": {"sealed"},
    "PROVED": {"proved"},
    "CONDITIONAL": {"conditional"},
    "FROZEN": {"assumed", "frozen"},
    "DRAFT_SORRY": {"draft", "draft_sorry", "frozen-statement"},
}
CANONICAL_STATUS = {
    "SEALED": "sealed",
    "PROVED": "proved",
    "CONDITIONAL": "conditional",
    "FROZEN": "assumed",
    "DRAFT_SORRY": "frozen-statement",
}

_LEAN_LINE_RE = re.compile(r'^(?P<indent>\s*)lean:\s*"(?P<val>.*)"\s*$')
_STATUS_LINE_RE = re.compile(r'^(?P<indent>\s*)status:\s*"(?P<val>[^"]*)"\s*$')


def _check_formalization_yaml(res: Result, cfg: RepoConfig, write: bool) -> None:
    path = cfg.root / "formalization.yaml"
    if not path.exists():
        return
    text = path.read_text(encoding="utf-8")
    lines = text.split("\n")
    anchor = next((i for i, l in enumerate(lines) if l == "alignment:"), None)
    if anchor is None:
        return  # nothing under an `alignment:` key to own

    by_decl = {}
    for n in cfg.nodes:
        for d in n.decls:
            by_decl[d] = n

    touched = False
    current_names: list[str] | None = None
    for i in range(anchor, len(lines)):
        line = lines[i]
        m = _LEAN_LINE_RE.match(line)
        if m:
            current_names = [s.strip() for s in m.group("val").split(";") if s.strip()]
            continue
        m = _STATUS_LINE_RE.match(line)
        if not m or current_names is None:
            continue
        names, current_names = current_names, None
        resolved = [(nm, by_decl[nm]) for nm in names if nm in by_decl]
        if not resolved:
            continue  # `lean:` names no manifest node yet — declared future work
        res.count()
        val = m.group("val")
        bad = [
            (nm, nd) for nm, nd in resolved
            if val not in STATUS_SYNONYMS.get(nd.state, set())
        ]
        if not bad:
            continue
        fixed = False
        if write:
            states = {nd.state for _, nd in resolved}
            if len(states) == 1:
                new_val = CANONICAL_STATUS.get(next(iter(states)))
                if new_val:
                    lines[i] = f'{m.group("indent")}status: "{new_val}"'
                    touched = True
                    fixed = True
        if not fixed:
            res.fail(
                f"formalization.yaml:{i + 1}: alignment status {val!r} disagrees "
                "with the manifest for "
                + ", ".join(f"{nm} (manifest state {nd.state})" for nm, nd in bad)
            )

    if touched:
        path.write_text("\n".join(lines), encoding="utf-8")


# ---- entry point ------------------------------------------------------------


def check(res: Result, cfg: RepoConfig, write: bool = False) -> None:
    res.total = len(cfg.nodes)

    _sync_markdown_file(cfg.root / "README.md", cfg, res, write, required=True)
    _sync_markdown_file(cfg.root / "CORRESPONDENCE.md", cfg, res, write, required=True)
    _sync_markdown_file(cfg.root / "PROOF.md", cfg, res, write, required=False)

    _check_formalization_yaml(res, cfg, write)


def main(argv: list[str]) -> int:
    args = argv[1:]
    write = "--write" in args
    positional = [a for a in args if not a.startswith("--")]
    root = positional[0] if positional else "."
    cfg = load(root)
    return run("sync_docs", check, cfg, write=write)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
