import CERW.Support.Norm.Freedman
import CERW.Support.Norm.DriftSite
import CERW.Support.Norm.VectorBound
import CERW.Support.Norm.MoreauCap
import CERW.Support.Norm.Geometry
import CERW.Support.Norm.Crossing
import CERW.Support.Norm.BallLayer
import CERW.Support.Norm.Radial
import CERW.Support.Norm.OuterCrossing
import CERW.Support.Norm.CellGradient
import CERW.Support.Norm.Coarse
import CERW.Support.Norm.LocalTime
import CERW.Support.Norm.ContactPotential
import CERW.Support.Norm.ShapeRates
